services:
  appPostgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=myDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data