replicaCount: 1

image:
  repository: me2stafa/demo-employee
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 9090

postgres:
  host: postgres-service
  port: 5432
  database: myDB
  username: postgres
  passwordSecret: db-credentials
  passwordSecretKey: DB_PASSWORD

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false  # Set this to true if you want ingress enabled
  annotations: {}
  hosts:
    - host: demo-employee.local
      paths:
        - /
  tls: []

autoscaling:
  enabled: false  # Set to true if you want Horizontal Pod Autoscaling (HPA) enabled
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
