apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-employee.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo-employee.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "demo-employee.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "demo-employee.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ .Values.postgres.host }}
            - name: DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: DB_DATABASE
              value: {{ .Values.postgres.database }}
            - name: DB_USERNAME
              value: {{ .Values.postgres.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecret }}
                  key: {{ .Values.postgres.passwordSecretKey }}
