apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-employee.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo-employee.name" . }}
    helm.sh/chart: {{ include "demo-employee.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
